#include <format>
#include <string>
#include <string_view>
#include <vector>

#include "p3a/pack.h"
#include "p3a/structs.h"
#include "sen/file_getter.h"
#include "sen4/tbl.h"
#include "util/hash/sha1.h"
#include "util/text.h"

extern "C" {
__declspec(dllexport) char SenPatcherFix_0_magic[] = "Fix errors in craft descriptions.";
}

namespace SenLib::Sen4::FileFixes::t_magic {
bool TryApply(const SenPatcher::GetCheckedFileCallback& getCheckedFile,
              std::vector<SenPatcher::P3APackFile>& result) {
    try {
        auto file = getCheckedFile(
            "data/text/dat_en/t_magic.tbl",
            162190,
            HyoutaUtils::Hash::SHA1FromHexString("2c71852245a5d7a10c5c7e687e4a095ac1f54b60"));
        if (!file) {
            return false;
        }

        auto& bin = file->Data;

        Tbl tbl_en(bin.data(), bin.size(), HyoutaUtils::EndianUtils::Endianness::LittleEndian);

        // Divine Knight stuff first

        // Spirit: Claims 25 CP but actually restores 30. Two copies (mech and partner)
        {
            auto& e = tbl_en.Entries[413];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 83, 2, "30");
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[414];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 83, 2, "30");
            e.Data = m.ToBinary();
        }

        // Tempete Rouge: Uses the autogenerated description, which is formatted weirdly. We can
        // copy and adapt the description from Moulin Rouge.
        {
            auto& e = tbl_en.Entries[438];
            auto& e2 = tbl_en.Entries[439];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 108) + m.desc;
            m.desc[48] = '3';
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 33, 2, "D");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 20, 1, "A");
            e.Data = m.ToBinary();
        }

        // Void Breaker/2: Listed as ADF/DEF down but usually DEF is listed first.
        {
            auto& e = tbl_en.Entries[444];
            MagicData m(e.Data.data(), e.Data.size());
            std::swap(m.desc[99], m.desc[103]);
            std::swap(m.desc[100], m.desc[104]);
            std::swap(m.desc[101], m.desc[105]);
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[445];
            MagicData m(e.Data.data(), e.Data.size());
            std::swap(m.desc[98], m.desc[102]);
            std::swap(m.desc[99], m.desc[103]);
            std::swap(m.desc[100], m.desc[104]);
            e.Data = m.ToBinary();
        }

        // Shock Breaker: Autogenerated, copy from Void Breaker
        {
            auto& e = tbl_en.Entries[443];
            auto& e2 = tbl_en.Entries[444];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 129) + m.desc;
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 124, " - #11CDelay +10#0C");
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 70, 23);
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 35, 1, "A+");
            e.Data = m.ToBinary();
        }

        // Power Smash: Autogenerated, copy from Chaos Saber
        {
            auto& e = tbl_en.Entries[446];
            auto& e2 = tbl_en.Entries[449];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 96) + m.desc;
            m.desc[48] = '7';
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 35, "+");
            m.desc[21] = 'B';
            e.Data = m.ToBinary();
        }

        // Salamander: Autogenerated, copy from Chaos Saber
        {
            auto& e = tbl_en.Entries[447];
            auto& e2 = tbl_en.Entries[449];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 96) + m.desc;
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 91, " - #11CDelay +10#0C");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 75, 6, "Burn");
            m.desc[48] = '1';
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 34, 1, "A+");
            m.desc[21] = 'S';
            e.Data = m.ToBinary();
        }

        // Resonant Beat: Swap the two effects so the immediate heal is listed before the over-time
        // one.
        {
            auto& e = tbl_en.Entries[481];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::MoveSubstring(m.desc, 61, 26, 25);
            e.Data = m.ToBinary();
        }

        // Resounding Beat: Autogenerated, copy from Resonant Beat
        {
            auto& e = tbl_en.Entries[480];
            auto& e2 = tbl_en.Entries[481];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 91) + m.desc;
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 20, 3, "Self");
            e.Data = m.ToBinary();
        }

        // Wild Rage: Autogenerated, copy from Unbound Rage
        {
            auto& e = tbl_en.Entries[487];
            auto& e2 = tbl_en.Entries[495];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 93) + m.desc;
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 29, 32);
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 35, 1, "12");
            e.Data = m.ToBinary();
        }

        // All of these say 'One' as the target but they can only target yourself, so it'd be nicer
        // to say 'Self'.
        for (int idx : {415, 416, 482, 483, 486, 487, 488, 493, 494, 495, 496, 498}) {
            auto& e = tbl_en.Entries[static_cast<size_t>(idx)];
            MagicData m(e.Data.data(), e.Data.size());
            auto pos = m.desc.find("One");
            if (pos != std::string::npos) {
                m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, pos, 3, "Self");
            }
            e.Data = m.ToBinary();
        }

        // A lot of the Divine Knight attacks have the 'Unblockable' trait that is completely
        // omitted in the English descriptions. Fix that.
        for (size_t i = 0; i < tbl_en.Entries.size(); ++i) {
            auto& e = tbl_en.Entries[i];
            if (e.Name == "magic") {
                MagicData m(e.Data.data(), e.Data.size());
                if (m.idx >= 5050 && m.idx <= 5545 && m.effects[1].idx == 192
                    && m.flags.find('Z') != std::string::npos) {
                    auto endpos = m.desc.find("]");
                    if (endpos != std::string::npos && endpos > 0) {
                        m.desc = HyoutaUtils::TextUtils::Insert(
                            m.desc, endpos - 1, " - #11CUnblockable#0C");
                        e.Data = m.ToBinary();
                    }
                }
            }
        }

        // fix a common spacing error
        for (size_t i = 0; i < tbl_en.Entries.size(); ++i) {
            auto& e = tbl_en.Entries[i];
            if (e.Name == "magic") {
                MagicData m(e.Data.data(), e.Data.size());
                if (m.desc.find("-#11C") != std::string::npos) {
                    m.desc = HyoutaUtils::TextUtils::Replace(m.desc, "-#11C", "- #11C");
                    e.Data = m.ToBinary();
                }
            }
        }

        // These weirdly use a & instead of a - to split the effects
        for (int idx : {94, 98, 114, 119, 251}) {
            auto& e = tbl_en.Entries[static_cast<size_t>(idx)];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Replace(m.desc, "&", "-");
            e.Data = m.ToBinary();
        }

        // Balance Down is inconsistently formatted with every other status effect. Fix this.
        for (size_t i = 0; i < tbl_en.Entries.size(); ++i) {
            auto& e = tbl_en.Entries[i];
            if (e.Name == "magic") {
                MagicData m(e.Data.data(), e.Data.size());
                auto bd = m.desc.find("Balance Down");
                if (bd != std::string::npos) {
                    auto nextOpenParens = m.desc.find('(', bd + 12);
                    if (nextOpenParens != std::string::npos) {
                        auto nextCloseParens = m.desc.find(')', nextOpenParens + 1);
                        if (nextCloseParens != std::string::npos) {
                            auto contents = std::string_view(m.desc).substr(
                                nextOpenParens + 1, nextCloseParens - (nextOpenParens + 1));
                            auto percent = contents.find('%');
                            if (percent == std::string_view::npos) {
                                // no percent, this is missing a "(100%)"
                                m.desc = HyoutaUtils::TextUtils::Insert(
                                    m.desc, nextOpenParens, "(100%) ");
                            } else {
                                // this may have an extra 'chance' after the percent
                                m.desc = HyoutaUtils::TextUtils::Remove(
                                    m.desc,
                                    nextOpenParens + percent + 2,
                                    nextCloseParens - (nextOpenParens + percent + 2));
                            }
                            e.Data = m.ToBinary();
                        }
                    }
                }
            }
        }

        // Crimson Slash: Burn is 20%, not 30%
        {
            auto& e = tbl_en.Entries[69];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc[104] = '2';
            e.Data = m.ToBinary();
        }

        // Demon Unchained: Missing space between "(L)" and "(3 turns)"
        {
            auto& e = tbl_en.Entries[74];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 64, " ");
            e.Data = m.ToBinary();
        }

        // Rosetta Arrow: This is completely wrong, it's using Flamberge's stats.
        {
            auto& e = tbl_en.Entries[96];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 118, " - #11CCritical rate+25%#0C");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 112, 1, "5");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 67, 1, "M+");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 48, 1, "2");
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 35, "+");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 20, 2, "A");
            e.Data = m.ToBinary();
        }

        // True/Radiant Wings: The HP recovery is over time, not instant.
        {
            auto& e = tbl_en.Entries[114];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 72, " (4 turns)");
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[119];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 73, " (4 turns)");
            e.Data = m.ToBinary();
        }

        // Cross Break: Power is C+, not C++
        {
            auto& e = tbl_en.Entries[196];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 23, 1);
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[207];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 23, 1);
            e.Data = m.ToBinary();
        }

        // Twilit Blades: Power E, not D
        {
            auto& e = tbl_en.Entries[215];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 20, 1, "E");
            e.Data = m.ToBinary();
        }

        // Tempest Edge: Power A+, not S
        {
            auto& e = tbl_en.Entries[217];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 21, 1, "A+");
            e.Data = m.ToBinary();
        }

        // Summon Kestrel 2: Power SSS+, not SS
        {
            auto& e = tbl_en.Entries[247];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 23, "S+");
            e.Data = m.ToBinary();
        }

        // Rumbling Smash: Faint is 20%, not 30%
        {
            auto& e = tbl_en.Entries[249];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 105, 1, "2");
            e.Data = m.ToBinary();
        }

        // Reaper's Whirlwind 2: Typo, "(60)%" should be "(60%)"
        {
            auto& e = tbl_en.Entries[257];
            MagicData m(e.Data.data(), e.Data.size());
            std::swap(m.desc[108], m.desc[109]);
            e.Data = m.ToBinary();
        }

        // Requiem Shot: Extra linebreak.
        {
            auto& e = tbl_en.Entries[279];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 171, 1, " ");
            e.Data = m.ToBinary();
        }

        // Happy Trigger: Extra linebreak.
        {
            auto& e = tbl_en.Entries[281];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 121, 1, " ");
            e.Data = m.ToBinary();
        }

        // Akashic Star: Extra linebreak.
        {
            auto& e = tbl_en.Entries[282];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 136, 1, " ");
            e.Data = m.ToBinary();
        }

        // Umbral Butterflies: Dash is colored wrong.
        {
            auto& e = tbl_en.Entries[270];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 108, 3, "#0C - #11C");
            e.Data = m.ToBinary();
        }

        // Mortal Mirage: Stats are wrong.
        {
            auto& e = tbl_en.Entries[265];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 49, 2, "30");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 34, 2, "D");
            e.Data = m.ToBinary();
        }

        // Frigid Rain: Stats are wrong.
        {
            auto& e = tbl_en.Entries[266];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 47, 3, "Yes");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 33, 2, "A");
            e.Data = m.ToBinary();
        }

        // Kaleido Force: Stats are wrong.
        {
            auto& e = tbl_en.Entries[267];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 34, 2, "D");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 21, 1, "SSS+");
            e.Data = m.ToBinary();
        }

        // Laevateinn: Stats are wrong.
        {
            auto& e = tbl_en.Entries[276];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 48, 2, "+30%");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 34, 2, "B");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 21, 1, "A");
            e.Data = m.ToBinary();
        }

        // Spell Card: Extra linebreak.
        {
            auto& e = tbl_en.Entries[277];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 62, 1, " ");
            e.Data = m.ToBinary();
        }

        // Rubrum Knight: Extra linebreak. Stats are wrong.
        {
            auto& e = tbl_en.Entries[278];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 169, 1, " ");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 34, 2, "D");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 21, 1, "SSS+");
            e.Data = m.ToBinary();
        }

        // Southern Cross: Autogenerated weirdly formatted description, manually write it out.
        {
            auto& e = tbl_en.Entries[559];
            auto& e2 = tbl_en.Entries[568];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 71) + m.desc;
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(
                m.desc, 53, 10, "Restores 30% HP/EP#0C - #11CCP+30");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 39, 1, "7");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 13, 1, "8");
            e.Data = m.ToBinary();
        }

        // Cold Nail: Missing (Set) for area.
        {
            auto& e = tbl_en.Entries[296];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 66, " (Set)");
            e.Data = m.ToBinary();
        }

        // Piercing Blitz: Stats are wrong.
        {
            auto& e = tbl_en.Entries[297];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 49, 2, "+20%");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 35, 2, "D");
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 22, 1);
            e.Data = m.ToBinary();
        }

        // Javelin Throw: Claims (Set) but isn't.
        {
            auto& e = tbl_en.Entries[353];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 69, 6);
            e.Data = m.ToBinary();
        }

        // Brutal Spin: Claims (Set) but isn't.
        {
            auto& e = tbl_en.Entries[355];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 67, 6);
            e.Data = m.ToBinary();
        }

        // Destructive Buster: Claims 4B+ power, not sure how that got here...
        {
            auto& e = tbl_en.Entries[356];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 21, 1);
            e.Data = m.ToBinary();
        }

        // The 5 existing dis-orders all have descriptions and 4 of them are wrong lol, and all of
        // them call them Anti-Order instead of Dis-Order. I don't think this actually matters, I
        // don't think you can ever see these naturally, but might as well fix them...
        {
            auto& e = tbl_en.Entries[581];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, m.desc.size() - 10, 4, "Dis");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 35, 1, "1");
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[582];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, m.desc.size() - 10, 4, "Dis");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 40, 1, "1");
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[583];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, m.desc.size() - 10, 4, "Dis");
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 34, " ");
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[584];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, m.desc.size() - 10, 4, "Dis");
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 35, 1);
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[585];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, m.desc.size() - 10, 4, "Dis");
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 40, 1);
            e.Data = m.ToBinary();
        }

        // Gale, Arcane Gale, Howling Heavens, True Howling Heavens: These have autogenerated
        // descriptions and they're *technically* fine, but I want to add a space for "Delay+2" and
        // similar so we need to write them out.
        {
            auto& e = tbl_en.Entries[71];
            auto& e2 = tbl_en.Entries[84];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 120) + m.desc;
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 95, 20);
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 91, 1, "2");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 49, 2, "5");
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 35, 1);
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 21, 1, "B+");
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[77];
            auto& e2 = tbl_en.Entries[84];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 120) + m.desc;
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 95, 20);
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 91, 1, "2");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 49, 2, "5");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 21, 1, "D+");
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[161];
            auto& e2 = tbl_en.Entries[84];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 120) + m.desc;
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 95, 20);
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 91, 1, "8");
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 85, "Absolute ");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 64, 11, "ll");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 48, 4, "No");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 34, 2, "D");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 21, 1, "4S");
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[166];
            auto& e2 = tbl_en.Entries[84];
            MagicData m(e.Data.data(), e.Data.size());
            MagicData m2(e2.Data.data(), e2.Data.size());
            m.flags += 'Z';
            m.desc = m2.desc.substr(0, 120) + m.desc;
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 95, 20);
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 91, 1, "12");
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 85, "Absolute ");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 64, 11, "ll");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 48, 4, "No");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 34, 2, "D");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 21, 1, "4S+");
            e.Data = m.ToBinary();
        }

        // Unbound Rage: The CP recovery is gradual (2 turns)
        {
            auto& e = tbl_en.Entries[251];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 35, " (2 turns)");
            e.Data = m.ToBinary();
        }

        // Remedy Fantasia/2, Aura Rain: These are healing S-Crafts that have extra effects at 200
        // CP and they're listed *really strangely*, in parenthesis next to an unrelated effect.
        // Make this more sensible. Aura Rain also gets some extra formatting fixes (Cures All ->
        // Cures ailments, Restores All HP -> Restores all HP)
        {
            auto& e = tbl_en.Entries[106];
            MagicData m(e.Data.data(), e.Data.size());
            std::string color = m.desc.substr(20, 10);
            std::string effect = m.desc.substr(70, 23);
            effect = "Restores " + HyoutaUtils::TextUtils::Insert(effect, 3, " HP");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 65, 29, color + effect);
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[110];
            MagicData m(e.Data.data(), e.Data.size());
            std::string color = m.desc.substr(20, 10);
            std::string effect = m.desc.substr(70, 23);
            effect = "Restores " + HyoutaUtils::TextUtils::Insert(effect, 3, " HP");
            m.desc = HyoutaUtils::TextUtils::Insert(m.desc, 119, color + effect);
            m.desc = HyoutaUtils::TextUtils::Remove(m.desc, 65, 29);
            e.Data = m.ToBinary();
        }
        {
            auto& e = tbl_en.Entries[322];
            MagicData m(e.Data.data(), e.Data.size());
            std::string color = m.desc.substr(30, 10);
            std::string effect = m.desc.substr(76, 25);
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(
                m.desc, 71, 31, "ailments" + color + effect);
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 98, 1, "a");
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 49, 1, "a");
            e.Data = m.ToBinary();
        }

        // Spiral Arts: Restores All EP -> Restores all EP
        {
            auto& e = tbl_en.Entries[572];
            MagicData m(e.Data.data(), e.Data.size());
            m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(m.desc, 60, 1, "a");
            e.Data = m.ToBinary();
        }

        // Merge cases like "Poison (50%) Petrify (50%)" to "Poison/Petrify (50%)" like Reverie
        for (int idx : {14,  32,  104, 108, 132, 136, 177, 178, 179, 180, 217,
                        223, 237, 244, 250, 255, 257, 270, 276, 314, 316}) {
            auto& e = tbl_en.Entries[static_cast<size_t>(idx)];
            MagicData m(e.Data.data(), e.Data.size());
            auto firstPercentage = m.desc.find("%)");
            if (firstPercentage != std::string::npos) {
                auto next = std::string_view(m.desc).substr(firstPercentage + 2);
                size_t drop = 0;
                if (next.starts_with("#0C #11C")) {
                    drop = 8;
                } else if (next.starts_with(" ")) {
                    drop = 1;
                }
                if (drop > 0) {
                    auto openParens =
                        std::string_view(m.desc).substr(0, firstPercentage).find_last_of('(');
                    if (openParens != std::string_view::npos && openParens != 0) {
                        m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(
                            m.desc, openParens - 1, (firstPercentage - openParens) + 3 + drop, "/");
                        e.Data = m.ToBinary();
                    }
                }
            }
        }

        // Split cases like "Impede (100%) Burn (20%)" to "Impede (100%) - Burn (20%)" like Reverie
        for (int idx : {69,  75,  82,  86,  92,  96,  139, 143, 157, 163, 196, 202,
                        207, 210, 215, 222, 249, 256, 297, 330, 331, 438, 439, 440}) {
            auto& e = tbl_en.Entries[static_cast<size_t>(idx)];
            MagicData m(e.Data.data(), e.Data.size());
            auto firstPercentage = m.desc.find("%)");
            if (firstPercentage != std::string::npos) {
                auto next = std::string_view(m.desc).substr(firstPercentage + 2);
                size_t drop = 0;
                if (next.starts_with("#0C #11C")) {
                    drop = 8;
                } else if (next.starts_with(" ")) {
                    drop = 1;
                }
                if (drop > 0) {
                    m.desc = HyoutaUtils::TextUtils::ReplaceSubstring(
                        m.desc, firstPercentage + 2, drop, "#0C - #11C");
                    e.Data = m.ToBinary();
                }
            }
        }

        // Add a space for things like "Delay+10" -> "Delay +10"
        for (size_t i = 0; i < tbl_en.Entries.size(); ++i) {
            auto& e = tbl_en.Entries[i];
            if (e.Name == "magic") {
                MagicData m(e.Data.data(), e.Data.size());
                if (m.flags.find('Z') != std::string::npos) {
                    auto endpos = m.desc.find("]");
                    if (endpos != std::string::npos && endpos > 0) {
                        bool modified = false;
                        while (true) {
                            auto desc = std::string_view(m.desc).substr(0, endpos);
                            endpos = desc.find_last_of('+');
                            if (endpos == std::string::npos || endpos == 0) {
                                break;
                            }

                            const char c = m.desc[endpos - 1];
                            if (c >= 'a' && c <= 'z') {
                                m.desc = HyoutaUtils::TextUtils::Insert(m.desc, endpos, " ");
                                modified = true;
                            }
                        }
                        if (modified) {
                            e.Data = m.ToBinary();
                        }
                    }
                }
            }
        }


        // remove Z flag to compare with autogenerated descriptions
        // for (size_t i = 0; i < tbl_en.Entries.size(); ++i) {
        //     auto& e = tbl_en.Entries[i];
        //     if (e.Name == "magic") {
        //         MagicData m(e.Data.data(), e.Data.size());
        //         auto pos = m.flags.find('Z');
        //         if (pos != std::string::npos) {
        //             m.flags.erase(m.flags.begin() + pos);
        //         }
        //         e.Data = m.ToBinary();
        //     }
        // }

        std::vector<char> result_en_vec;
        HyoutaUtils::Stream::MemoryStream result_en(result_en_vec);
        tbl_en.WriteToStream(result_en, HyoutaUtils::EndianUtils::Endianness::LittleEndian);


        result.emplace_back(
            std::move(result_en_vec), file->Filename, SenPatcher::P3ACompressionType::LZ4);

        return true;
    } catch (...) {
        return false;
    }
}
} // namespace SenLib::Sen4::FileFixes::t_magic
